-- Generated by Macarchy. Do not edit.
return {
  black = 0xff1e1e2e,
  white = 0xffcdd6f4,
  red = 0xfff38ba8,
  green = 0xffa6e3a1,
  blue = 0xff89b4fa,
  yellow = 0xfff9e2af,
  orange = 0xfff6b6ab,
  magenta = 0xfff5c2e7,
  grey = 0xff585b70,
  transparent = 0x00000000,

  bar = {
    bg = 0xf01e1e2e,
    border = 0xff1e1e2e,
  },
  popup = {
    bg = 0xc01e1e2e,
    border = 0xff585b70,
  },
  bg1 = 0xff313244,
  bg2 = 0xff45475a,
}
