-- Generated by Macarchy. Do not edit.
return {
  black = 0xff1f1f28,
  white = 0xffdcd7ba,
  red = 0xffc34043,
  green = 0xff76946a,
  blue = 0xff7e9cd8,
  yellow = 0xffc0a36e,
  orange = 0xffc17158,
  magenta = 0xff957fb8,
  grey = 0xff54546d,
  transparent = 0x00000000,

  bar = {
    bg = 0xf01f1f28,
    border = 0xff1f1f28,
  },
  popup = {
    bg = 0xc01f1f28,
    border = 0xff54546d,
  },
  bg1 = 0xff223249,
  bg2 = 0xff363646,
}
