-- Generated by Macarchy. Do not edit.
return {
  black = 0xff1f1f28,
  white = 0xffdcd7ba,
  red = 0xffe82424,
  green = 0xff98bb6c,
  blue = 0xff7e9cd8,
  yellow = 0xffe6c384,
  orange = 0xffe77354,
  magenta = 0xff957fb8,
  grey = 0xff727169,
  transparent = 0x00000000,

  bar = {
    bg = 0xf01f1f28,
    border = 0xff1f1f28,
  },
  popup = {
    bg = 0xc01f1f28,
    border = 0xff727169,
  },
  bg1 = 0xff2a2a37,
  bg2 = 0xff363646,
}
