import Foundation

public struct RenderedTheme: Sendable {
  public let themeJSON: Data
  public let kittyConfiguration: String
}

public struct ThemeRenderer: Sendable {
  public init() {}

  public func render(package: ThemePackage, generationID: String) throws -> RenderedTheme {
    let normalized = NormalizedTheme(package: package, generationID: generationID)
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
    var json = try encoder.encode(normalized)
    json.append(0x0a)

    var kitty = [
      "# Generated by Macarchy. Do not edit.",
      "foreground \(package.terminal.foreground.rawValue)",
      "background \(package.terminal.background.rawValue)",
      "cursor \(package.terminal.cursor.rawValue)",
      "selection_foreground \(package.terminal.selectionForeground.rawValue)",
      "selection_background \(package.terminal.selectionBackground.rawValue)",
    ]
    kitty.append(
      contentsOf: package.terminal.ansi.enumerated().map {
        "color\($0.offset) \($0.element.rawValue)"
      })

    return RenderedTheme(themeJSON: json, kittyConfiguration: kitty.joined(separator: "\n") + "\n")
  }

  public func write(_ rendered: RenderedTheme, to outputRoot: URL) throws {
    let generated = outputRoot.appending(path: "generated", directoryHint: .isDirectory)
    try FileManager.default.createDirectory(at: generated, withIntermediateDirectories: true)
    try rendered.themeJSON.write(to: outputRoot.appending(path: "theme.json"), options: .atomic)
    try Data(rendered.kittyConfiguration.utf8).write(
      to: generated.appending(path: "kitty.conf"), options: .atomic)
  }
}
