import Foundation

public struct RenderedTheme: Sendable {
  public let themeJSON: Data
  public let kittyConfiguration: String

  var files: [String: Data] {
    [
      ThemeRenderer.kittyOutputPath: Data(kittyConfiguration.utf8),
      ThemeRenderer.themeOutputPath: themeJSON,
    ]
  }
}

public struct ThemeRenderer: Sendable {
  static let kittyOutputPath = "generated/kitty.conf"
  static let themeOutputPath = "theme.json"
  static let outputPaths = Set([kittyOutputPath, themeOutputPath])

  public init() {}

  public func render(package: ThemePackage, generationID: String) throws -> RenderedTheme {
    let normalized = NormalizedTheme(package: package, generationID: generationID)
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
    var json = try encoder.encode(normalized)
    json.append(0x0a)

    var kitty = [
      "# Generated by Macarchy. Do not edit.",
      "foreground \(package.terminal.foreground.rawValue)",
      "background \(package.terminal.background.rawValue)",
      "cursor \(package.terminal.cursor.rawValue)",
      "selection_foreground \(package.terminal.selectionForeground.rawValue)",
      "selection_background \(package.terminal.selectionBackground.rawValue)",
    ]
    kitty.append(
      contentsOf: package.terminal.ansi.enumerated().map {
        "color\($0.offset) \($0.element.rawValue)"
      })

    return RenderedTheme(themeJSON: json, kittyConfiguration: kitty.joined(separator: "\n") + "\n")
  }

  public func write(_ rendered: RenderedTheme, to outputRoot: URL) throws {
    for (path, data) in rendered.files {
      let output = outputRoot.appending(path: path)
      try FileManager.default.createDirectory(
        at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
      try data.write(to: output, options: .atomic)
    }
  }
}
