-- Generated by Macarchy. Do not edit.
return {
  black = 0xff1a1b26,
  white = 0xffa9b1d6,
  red = 0xfff7768e,
  green = 0xff9ece6a,
  blue = 0xff7aa2f7,
  yellow = 0xffe0af68,
  orange = 0xffeb927b,
  magenta = 0xffad8ee6,
  grey = 0xff414868,
  transparent = 0x00000000,

  bar = {
    bg = 0xf01a1b26,
    border = 0xff1a1b26,
  },
  popup = {
    bg = 0xc01a1b26,
    border = 0xff414868,
  },
  bg1 = 0xff24283b,
  bg2 = 0xff292e42,
}
