import Foundation

enum AtuinAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadConfiguration(URL)
  case configurationTooLarge(URL)
  case controlUnavailable(URL)
  case missingThemeSelection(String)

  var description: String {
    switch self {
    case .cannotReadConfiguration(let url):
      "Cannot read Atuin configuration at \(url.path)"
    case .configurationTooLarge(let url):
      "Atuin configuration at \(url.path) exceeds 1 MiB"
    case .controlUnavailable(let url):
      "Atuin is not executable at \(url.path)"
    case .missingThemeSelection(let selection):
      "Atuin configuration must select \(selection)"
    }
  }
}

package struct AtuinAdapter: Sendable {
  static let id = "atuin"
  package static let outputPath = "generated/atuin.toml"
  static let rendererVersion = 1
  package static let themeName = "macarchy-current"
  package static let selectionTable = "theme"
  package static let selectionKey = "name"
  static var liveExecutableURL: URL {
    preferredExternalOrHomebrewExecutableURL(
      homeDirectory: FileManager.default.homeDirectoryForCurrentUser,
      externalRelativePath: ".atuin/bin/atuin",
      homebrewExecutableName: "atuin"
    )
  }

  let root: URL
  let configurationDirectoryURL: URL
  let executableURL: URL
  let controlIsAvailable: @Sendable () -> Bool
  let processRunner: ProcessRunner

  private var configurationURL: URL {
    configurationDirectoryURL.appending(path: "config.toml")
  }

  private var themeLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: configurationDirectoryURL.appending(path: "themes/\(Self.themeName).toml"),
      destination: root.appending(path: "current/\(Self.outputPath)")
    )
  }

  func preflight() throws {
    guard controlIsAvailable() else {
      throw AtuinAdapterError.controlUnavailable(executableURL)
    }
    try themeLink.validate()
    guard Self.selectsTheme(in: try readConfiguration()) else {
      throw AtuinAdapterError.missingThemeSelection(
        "[theme] name = \"\(Self.themeName)\""
      )
    }
  }

  private var runtime: OrdinaryAdapterRuntime {
    OrdinaryAdapterRuntime(
      adapterID: Self.id,
      requirement: .required,
      preflight: preflight,
      isIntegrationDrift: Self.isIntegrationDrift
    )
  }

  func inspection() -> AdapterInspection {
    runtime.inspection(readyMessage: "Fresh Atuin search interfaces use the generated theme")
  }

  func reconciliation() -> AdapterReconciliation {
    runtime.reconciliation {
      let result = try processRunner.run(
        ProcessRequest(
          executableURL: executableURL,
          arguments: ["config", "get", "theme.name"],
          timeout: 1,
          environmentOverrides: ["ATUIN_CONFIG_DIR": configurationDirectoryURL.path]
        )
      )
      guard result.terminationStatus == 0, result.output == Self.themeName else {
        return AdapterOutcome(
          status: .failed,
          message: result.output.isEmpty ? "Atuin rejected its theme configuration" : result.output
        )
      }
      return AdapterOutcome(
        status: .applied,
        message: "Fresh Atuin search interfaces use the active palette"
      )
    }
  }

  static func render(package: ThemePackage) -> String {
    let semantic = package.semantic
    let ansi = package.terminal.ansi
    return """
      # Generated by Macarchy. Do not edit.
      [theme]
      name = "\(themeName)"

      [colors]
      AlertInfo = "\(semantic.success.rawValue)"
      AlertWarn = "\(semantic.warning.rawValue)"
      AlertError = "\(semantic.error.rawValue)"
      Annotation = "\(semantic.accent.rawValue)"
      Base = "\(semantic.text.rawValue)"
      Guidance = "\(semantic.mutedText.rawValue)"
      Important = "\(semantic.error.rawValue)"
      Title = "\(semantic.accent.rawValue)"
      Muted = "\(semantic.mutedText.rawValue)"
      SyntaxCommand = "\(semantic.success.rawValue)"
      SyntaxFlag = "\(semantic.info.rawValue)"
      SyntaxString = "\(semantic.warning.rawValue)"
      SyntaxVariable = "\(semantic.accent.rawValue)"
      SyntaxOperator = "\(ansi[6].rawValue)"
      SyntaxComment = "\(semantic.mutedText.rawValue)"

      """
  }

  private func readConfiguration() throws -> String {
    let resolvedURL = configurationURL.resolvingSymlinksInPath()
    let data: Data
    do {
      data = try BoundedRegularFile.read(at: resolvedURL).data
    } catch BoundedRegularFileError.tooLarge {
      throw AtuinAdapterError.configurationTooLarge(configurationURL)
    } catch {
      throw AtuinAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard let configuration = String(data: data, encoding: .utf8) else {
      throw AtuinAdapterError.cannotReadConfiguration(configurationURL)
    }
    return configuration
  }

  private static func selectsTheme(in configuration: String) -> Bool {
    let selection = CanonicalTOMLSelector(
      configuration: configuration,
      table: selectionTable,
      key: selectionKey
    )
    return selection.tableHeaderCount == 1 && selection.values == ["\"\(themeName)\""]
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, AtuinAdapterError.missingThemeSelection:
      true
    default:
      false
    }
  }
}
