import Foundation

enum BtopAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadConfiguration(URL)
  case configurationTooLarge(URL)
  case controlUnavailable(URL)
  case wrongThemeSelection(String)

  var description: String {
    switch self {
    case .cannotReadConfiguration(let url):
      "Cannot read btop configuration at \(url.path)"
    case .configurationTooLarge(let url):
      "btop configuration at \(url.path) exceeds 1 MiB"
    case .controlUnavailable(let url):
      "btop is not executable at \(url.path)"
    case .wrongThemeSelection(let expected):
      "btop color_theme must be \"\(expected)\""
    }
  }
}

package struct BtopAdapter: Sendable {
  static let id = "btop"
  package static let outputPath = "generated/btop.theme"
  static let rendererVersion = 1
  package static let themeName = "macarchy-current"
  package static let themeDirective = "color_theme = \"\(themeName)\""
  package static let themeFileName = "\(themeName).theme"
  static let liveExecutableURL = URL(filePath: "/opt/homebrew/bin/btop")

  private static let killallURL = URL(filePath: "/usr/bin/killall")

  let root: URL
  let configurationDirectoryURL: URL
  let executableURL: URL
  let controlIsAvailable: @Sendable () -> Bool
  let processRunner: ProcessRunner

  private var configurationURL: URL {
    configurationDirectoryURL.appending(path: "btop.conf")
  }

  private var themeLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: configurationDirectoryURL.appending(path: "themes/\(Self.themeFileName)"),
      destination: root.appending(path: "current/\(Self.outputPath)")
    )
  }

  func preflight() throws {
    guard controlIsAvailable() else {
      throw BtopAdapterError.controlUnavailable(executableURL)
    }
    try themeLink.validate()

    let lines = try readConfiguration().split(whereSeparator: \.isNewline)
    let selections = lines.compactMap { line -> String? in
      let content = line.split(separator: "#", maxSplits: 1).first?.trimmingCharacters(
        in: .whitespacesAndNewlines)
      guard let content else { return nil }
      let parts = content.split(separator: "=", maxSplits: 1).map {
        $0.trimmingCharacters(in: .whitespaces)
      }
      guard parts.count == 2, parts[0] == "color_theme" else { return nil }
      return parts[1]
    }
    guard selections == ["\"\(Self.themeName)\""] else {
      throw BtopAdapterError.wrongThemeSelection(Self.themeName)
    }
  }

  private var runtime: OrdinaryAdapterRuntime {
    OrdinaryAdapterRuntime(
      adapterID: Self.id,
      requirement: .required,
      preflight: preflight,
      isIntegrationDrift: Self.isIntegrationDrift
    )
  }

  func inspection() -> AdapterInspection {
    runtime.inspection(
      readyMessage: "btop uses the generated theme and supports live SIGUSR2 reload"
    )
  }

  func reconciliation() -> AdapterReconciliation {
    runtime.reconciliation {
      let reload = try processRunner.run(
        ProcessRequest(executableURL: Self.killallURL, arguments: ["-USR2", "btop"])
      )
      if reload.terminationStatus == 0 {
        return AdapterOutcome(status: .applied, message: "btop reloaded the active palette")
      }

      let stillRunning = try processRunner.run(
        ProcessRequest(executableURL: Self.killallURL, arguments: ["-0", "btop"])
      )
      guard stillRunning.terminationStatus == 0 else {
        return AdapterOutcome(
          status: .applied,
          message: "btop will use the active palette on next launch"
        )
      }
      return AdapterOutcome(
        status: .failed,
        message: reload.output.isEmpty ? "btop rejected its reload signal" : reload.output
      )
    }
  }

  static func render(package: ThemePackage) -> String {
    let semantic = package.semantic
    let ansi = package.terminal.ansi
    return """
      # Generated by Macarchy. Do not edit.
      theme[main_bg]="\(semantic.background.rawValue)"
      theme[main_fg]="\(semantic.text.rawValue)"
      theme[title]="\(semantic.text.rawValue)"
      theme[hi_fg]="\(semantic.accent.rawValue)"
      theme[selected_bg]="\(semantic.selection.rawValue)"
      theme[selected_fg]="\(semantic.text.rawValue)"
      theme[inactive_fg]="\(semantic.mutedText.rawValue)"
      theme[graph_text]="\(semantic.text.rawValue)"
      theme[meter_bg]="\(semantic.overlay.rawValue)"
      theme[proc_misc]="\(semantic.text.rawValue)"
      theme[cpu_box]="\(semantic.accent.rawValue)"
      theme[mem_box]="\(semantic.success.rawValue)"
      theme[net_box]="\(semantic.error.rawValue)"
      theme[proc_box]="\(semantic.info.rawValue)"
      theme[div_line]="\(semantic.border.rawValue)"
      theme[temp_start]="\(semantic.success.rawValue)"
      theme[temp_mid]="\(semantic.warning.rawValue)"
      theme[temp_end]="\(semantic.error.rawValue)"
      theme[cpu_start]="\(ansi[6].rawValue)"
      theme[cpu_mid]="\(ansi[4].rawValue)"
      theme[cpu_end]="\(semantic.accent.rawValue)"
      theme[free_start]="\(semantic.accent.rawValue)"
      theme[free_mid]="\(ansi[4].rawValue)"
      theme[free_end]="\(semantic.info.rawValue)"
      theme[cached_start]="\(semantic.info.rawValue)"
      theme[cached_mid]="\(ansi[4].rawValue)"
      theme[cached_end]="\(semantic.accent.rawValue)"
      theme[available_start]="\(semantic.warning.rawValue)"
      theme[available_mid]="\(ansi[1].rawValue)"
      theme[available_end]="\(semantic.error.rawValue)"
      theme[used_start]="\(semantic.success.rawValue)"
      theme[used_mid]="\(ansi[6].rawValue)"
      theme[used_end]="\(semantic.info.rawValue)"
      theme[download_start]="\(semantic.warning.rawValue)"
      theme[download_mid]="\(ansi[1].rawValue)"
      theme[download_end]="\(semantic.error.rawValue)"
      theme[upload_start]="\(semantic.success.rawValue)"
      theme[upload_mid]="\(ansi[6].rawValue)"
      theme[upload_end]="\(semantic.info.rawValue)"
      theme[process_start]="\(semantic.info.rawValue)"
      theme[process_mid]="\(ansi[4].rawValue)"
      theme[process_end]="\(semantic.accent.rawValue)"

      """
  }

  private func readConfiguration() throws -> String {
    let data: Data
    do {
      data = try BoundedRegularFile.read(at: configurationURL).data
    } catch BoundedRegularFileError.tooLarge {
      throw BtopAdapterError.configurationTooLarge(configurationURL)
    } catch {
      throw BtopAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard let configuration = String(data: data, encoding: .utf8) else {
      throw BtopAdapterError.cannotReadConfiguration(configurationURL)
    }
    return configuration
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, BtopAdapterError.wrongThemeSelection:
      true
    default:
      false
    }
  }
}
