import Foundation

enum EzaAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadShellConfiguration(URL)
  case configurationTooLarge(URL)
  case controlUnavailable(URL)
  case missingEnvironmentDirective(String)

  var description: String {
    switch self {
    case .cannotReadShellConfiguration(let url):
      "Cannot read shell configuration at \(url.path)"
    case .configurationTooLarge(let url):
      "Shell configuration at \(url.path) exceeds 1 MiB"
    case .controlUnavailable(let url):
      "eza is not executable at \(url.path)"
    case .missingEnvironmentDirective(let directive):
      "Shell configuration must contain '\(directive)'"
    }
  }
}

package struct EzaAdapter: Sendable {
  static let id = "eza"
  package static let outputPath = "generated/eza.yml"
  static let rendererVersion = 1
  package static let themeFileName = "theme.yml"
  static let liveExecutableURL = URL(filePath: "/opt/homebrew/bin/eza")

  package static func environmentDirective(configurationDirectoryURL: URL) -> String {
    "export EZA_CONFIG_DIR=\"\(configurationDirectoryURL.path)\""
  }

  let root: URL
  let configurationDirectoryURL: URL
  let shellConfigurationURL: URL
  let executableURL: URL
  let controlIsAvailable: @Sendable () -> Bool
  let processRunner: ProcessRunner

  private var themeLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: configurationDirectoryURL.appending(path: Self.themeFileName),
      destination: root.appending(path: "current/\(Self.outputPath)")
    )
  }

  func preflight() throws {
    guard controlIsAvailable() else {
      throw EzaAdapterError.controlUnavailable(executableURL)
    }
    try themeLink.validate()

    let shell = try readShellConfiguration()
    let directive = Self.environmentDirective(configurationDirectoryURL: configurationDirectoryURL)
    guard containsExactLine(directive, in: shell) else {
      throw EzaAdapterError.missingEnvironmentDirective(directive)
    }
  }

  private var runtime: OrdinaryAdapterRuntime {
    OrdinaryAdapterRuntime(
      adapterID: Self.id,
      requirement: .required,
      preflight: preflight,
      isIntegrationDrift: Self.isIntegrationDrift
    )
  }

  func inspection() -> AdapterInspection {
    runtime.inspection(readyMessage: "Fresh eza invocations read the canonical palette")
  }

  func reconciliation() -> AdapterReconciliation {
    runtime.reconciliation {
      let result = try processRunner.run(
        ProcessRequest(
          executableURL: executableURL,
          arguments: ["--color=always", "--oneline", themeLink.url.path],
          timeout: 1,
          environmentOverrides: ["EZA_CONFIG_DIR": configurationDirectoryURL.path]
        )
      )
      guard result.terminationStatus == 0 else {
        return AdapterOutcome(
          status: .failed,
          message: result.output.isEmpty ? "eza rejected the active palette" : result.output
        )
      }
      return AdapterOutcome(
        status: .applied,
        message: "Fresh eza invocations use the active palette"
      )
    }
  }

  static func render(package: ThemePackage) -> String {
    let semantic = package.semantic
    let ansi = package.terminal.ansi
    func style(_ color: SRGBColor) -> String {
      "{ foreground: \"\(color.rawValue)\" }"
    }

    return """
      # Generated by Macarchy. Do not edit.
      colourful: true

      filekinds:
        normal: \(style(semantic.text))
        directory: \(style(ansi[4]))
        symlink: \(style(ansi[6]))
        pipe: \(style(semantic.mutedText))
        block_device: \(style(semantic.warning))
        char_device: \(style(semantic.warning))
        socket: \(style(semantic.overlay))
        special: \(style(semantic.accent))
        executable: \(style(semantic.success))
        mount_point: \(style(semantic.info))

      perms:
        user_read: \(style(semantic.text))
        user_write: \(style(semantic.warning))
        user_execute_file: \(style(semantic.success))
        user_execute_other: \(style(semantic.success))
        group_read: \(style(semantic.mutedText))
        group_write: \(style(semantic.warning))
        group_execute: \(style(semantic.success))
        other_read: \(style(semantic.mutedText))
        other_write: \(style(semantic.warning))
        other_execute: \(style(semantic.success))
        special_user_file: \(style(semantic.accent))
        special_other: \(style(semantic.error))
        attribute: \(style(semantic.mutedText))

      size:
        major: \(style(semantic.mutedText))
        minor: \(style(ansi[6]))
        number_byte: \(style(semantic.text))
        number_kilo: \(style(semantic.info))
        number_mega: \(style(ansi[4]))
        number_giga: \(style(semantic.accent))
        number_huge: \(style(semantic.error))
        unit_byte: \(style(semantic.mutedText))
        unit_kilo: \(style(semantic.info))
        unit_mega: \(style(ansi[4]))
        unit_giga: \(style(semantic.accent))
        unit_huge: \(style(semantic.error))

      users:
        user_you: \(style(semantic.text))
        user_root: \(style(semantic.error))
        user_other: \(style(semantic.accent))
        group_yours: \(style(semantic.mutedText))
        group_other: \(style(semantic.overlay))
        group_root: \(style(semantic.error))

      links:
        normal: \(style(ansi[6]))
        multi_link_file: \(style(semantic.info))

      git:
        new: \(style(semantic.success))
        modified: \(style(semantic.warning))
        deleted: \(style(semantic.error))
        renamed: \(style(ansi[6]))
        typechange: \(style(semantic.accent))
        ignored: \(style(semantic.mutedText))
        conflicted: \(style(semantic.error))

      git_repo:
        branch_main: \(style(semantic.text))
        branch_other: \(style(semantic.accent))
        git_clean: \(style(semantic.success))
        git_dirty: \(style(semantic.error))

      security_context:
        colon: \(style(semantic.mutedText))
        user: \(style(semantic.text))
        role: \(style(semantic.accent))
        typ: \(style(semantic.overlay))
        range: \(style(semantic.accent))

      file_type:
        image: \(style(semantic.warning))
        video: \(style(semantic.error))
        music: \(style(semantic.success))
        lossless: \(style(ansi[6]))
        crypto: \(style(semantic.error))
        document: \(style(semantic.text))
        compressed: \(style(semantic.accent))
        temp: \(style(semantic.mutedText))
        compiled: \(style(semantic.info))
        build: \(style(semantic.overlay))
        source: \(style(ansi[4]))

      punctuation: \(style(semantic.mutedText))
      date: \(style(semantic.warning))
      inode: \(style(semantic.mutedText))
      blocks: \(style(semantic.overlay))
      header: \(style(semantic.text))
      octal: \(style(ansi[6]))
      flags: \(style(semantic.accent))

      symlink_path: \(style(ansi[6]))
      control_char: \(style(semantic.info))
      broken_symlink: \(style(semantic.error))
      broken_path_overlay: \(style(semantic.overlay))

      """
  }

  private func readShellConfiguration() throws -> String {
    try AdapterConfigurationFile.readUTF8(
      at: shellConfigurationURL,
      tooLarge: EzaAdapterError.configurationTooLarge(shellConfigurationURL),
      unreadable: EzaAdapterError.cannotReadShellConfiguration(shellConfigurationURL)
    )
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, EzaAdapterError.missingEnvironmentDirective:
      true
    default:
      false
    }
  }
}
