import Foundation

enum KittyAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadConfiguration(URL)
  case configurationTooLarge(URL)
  case missingInclude(String)

  var description: String {
    switch self {
    case .cannotReadConfiguration(let url):
      "Cannot read Kitty configuration at \(url.path)"
    case .configurationTooLarge(let url):
      "Kitty configuration at \(url.path) exceeds 1 MiB"
    case .missingInclude(let directive):
      "Kitty configuration must contain '\(directive)'"
    }
  }
}

struct KittyAdapter: Sendable {
  private static let maximumConfigurationSize = 1_048_576
  private static let killallURL = URL(filePath: "/usr/bin/killall")
  static let id = "kitty"
  static let outputPath = "generated/kitty.conf"
  static let rendererVersion = 1

  let configurationURL: URL
  let includeDirective: String
  let processRunner: ProcessRunner

  func preflight() throws {
    let values: URLResourceValues
    do {
      values = try configurationURL.resourceValues(forKeys: [.isRegularFileKey])
    } catch {
      throw KittyAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard values.isRegularFile == true else {
      throw KittyAdapterError.cannotReadConfiguration(configurationURL)
    }

    let data: Data
    do {
      let handle = try FileHandle(forReadingFrom: configurationURL)
      defer { try? handle.close() }
      data = try handle.read(upToCount: Self.maximumConfigurationSize + 1) ?? Data()
    } catch {
      throw KittyAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard data.count <= Self.maximumConfigurationSize else {
      throw KittyAdapterError.configurationTooLarge(configurationURL)
    }
    guard let configuration = String(data: data, encoding: .utf8) else {
      throw KittyAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard
      configuration.split(separator: "\n").contains(where: { line in
        line.trimmingCharacters(in: .whitespaces) == includeDirective
      })
    else {
      throw KittyAdapterError.missingInclude(includeDirective)
    }
  }

  func inspection() -> AdapterInspection {
    do {
      try preflight()
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required
      )
    } catch {
      let status: AdapterInspectionStatus
      if case KittyAdapterError.missingInclude = error {
        status = .drifted
      } else {
        status = .failed
      }
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        status: status,
        message: String(describing: error)
      )
    }
  }

  func reconciliation() -> AdapterReconciliation {
    AdapterReconciliation(id: Self.id, requirement: .required) {
      do {
        try preflight()
      } catch {
        return AdapterOutcome(status: .drifted, message: String(describing: error))
      }

      let reload = try await processRunner.run(
        ProcessRequest(
          executableURL: Self.killallURL,
          arguments: ["-USR1", "kitty"]
        )
      )
      guard reload.terminationStatus != 0 else {
        return AdapterOutcome(status: .applied)
      }

      let stillRunning = try await processRunner.run(
        ProcessRequest(
          executableURL: Self.killallURL,
          arguments: ["-0", "kitty"]
        )
      )
      guard stillRunning.terminationStatus == 0 else {
        return AdapterOutcome(status: .applied)
      }
      return AdapterOutcome(
        status: .failed,
        message: reload.output.isEmpty ? "Kitty rejected its reload signal" : reload.output
      )
    }
  }

  static func render(package: ThemePackage) -> String {
    var lines = [
      "# Generated by Macarchy. Do not edit.",
      "foreground \(package.terminal.foreground.rawValue)",
      "background \(package.terminal.background.rawValue)",
      "cursor \(package.terminal.cursor.rawValue)",
      "selection_foreground \(package.terminal.selectionForeground.rawValue)",
      "selection_background \(package.terminal.selectionBackground.rawValue)",
    ]
    lines.append(
      contentsOf: package.terminal.ansi.enumerated().map {
        "color\($0.offset) \($0.element.rawValue)"
      }
    )
    return lines.joined(separator: "\n") + "\n"
  }
}

struct ProcessRequest: Equatable, Sendable {
  let executableURL: URL
  let arguments: [String]
}

struct ProcessResult: Equatable, Sendable {
  let terminationStatus: Int32
  let output: String
}

struct ProcessRunner: Sendable {
  let run: @Sendable (ProcessRequest) async throws -> ProcessResult

  static let live = ProcessRunner { request in
    try Task.checkCancellation()
    let process = Process()
    let output = Pipe()
    process.executableURL = request.executableURL
    process.arguments = request.arguments
    process.standardOutput = output
    process.standardError = output
    try process.run()
    let data = output.fileHandleForReading.readDataToEndOfFile()
    process.waitUntilExit()
    try Task.checkCancellation()
    return ProcessResult(
      terminationStatus: process.terminationStatus,
      output: String(decoding: data, as: UTF8.self).trimmingCharacters(
        in: .whitespacesAndNewlines)
    )
  }
}
