import Foundation

enum NeovimAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadConfiguration(URL)
  case configurationTooLarge(URL)
  case controlUnavailable(URL)
  case invalidMapping(String)
  case missingIntegration(String)
  case missingMapping

  var description: String {
    switch self {
    case .cannotReadConfiguration(let url):
      "Cannot read Neovim theme configuration at \(url.path)"
    case .configurationTooLarge(let url):
      "Neovim theme configuration at \(url.path) exceeds 1 MiB"
    case .controlUnavailable(let url):
      "Neovim is not executable at \(url.path)"
    case .invalidMapping(let mapping):
      "Neovim mapping '\(mapping)' must be a colorscheme name"
    case .missingIntegration(let directive):
      "Neovim theme configuration must contain '\(directive)'"
    case .missingMapping:
      "Theme package must define a Neovim mapping"
    }
  }
}

struct NeovimAdapter: Sendable {
  static let id = "neovim"
  static let integrationDirective = "local current = macarchy.watch()"
  static let outputPath = "generated/neovim.lua"
  static let rendererVersion = 2
  static let liveExecutableURL = URL(filePath: "/opt/homebrew/bin/nvim")

  let root: URL
  let configurationDirectoryURL: URL
  let executableURL: URL
  let controlIsAvailable: @Sendable () -> Bool
  let processRunner: ProcessRunner

  private var configurationURL: URL {
    configurationDirectoryURL.appending(path: "lua/plugins/colorscheme.lua")
  }

  private var themeLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: configurationDirectoryURL.appending(path: "lua/macarchy/current.lua"),
      destination: root.appending(path: "current/\(Self.outputPath)")
    )
  }

  func preflight() throws {
    guard controlIsAvailable() else {
      throw NeovimAdapterError.controlUnavailable(executableURL)
    }
    try themeLink.validate()
    guard Self.containsLine(Self.integrationDirective, in: try readConfiguration()) else {
      throw NeovimAdapterError.missingIntegration(Self.integrationDirective)
    }
  }

  func inspection() -> AdapterInspection {
    do {
      try preflight()
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        message: "Neovim watches the canonical theme pointer for live colorscheme changes"
      )
    } catch {
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        status: Self.isIntegrationDrift(error) ? .drifted : .failed,
        message: String(describing: error)
      )
    }
  }

  func reconciliation() -> AdapterReconciliation {
    AdapterReconciliation(id: Self.id, requirement: .required) {
      do {
        try preflight()
      } catch {
        return AdapterOutcome(
          status: Self.isIntegrationDrift(error) ? .drifted : .failed,
          message: String(describing: error)
        )
      }

      let manifest = try ReconciliationStatusStore(root: root).activeManifest()
      let marker = "MACARCHY_THEME=\(manifest.generationID):\(manifest.themeID)"
      let result = try processRunner.run(
        ProcessRequest(
          executableURL: executableURL,
          arguments: [
            "--headless",
            "+lua local ok, theme = pcall(require('config.macarchy-theme').verify); if ok then io.write('MACARCHY_THEME=' .. theme.generation_id .. ':' .. theme.theme_id) else io.stderr:write(theme); vim.cmd.cquit() end",
            "+qa",
          ],
          timeout: 5
        )
      )
      guard result.terminationStatus == 0, result.output.contains(marker) else {
        return AdapterOutcome(
          status: .failed,
          message: result.output.isEmpty
            ? "Neovim rejected the active colorscheme configuration" : result.output
        )
      }
      return AdapterOutcome(
        status: .applied,
        message:
          "Neovim validated the active colorscheme; running sessions repaint through the pointer watcher"
      )
    }
  }

  static func render(package: ThemePackage, generationID: String) throws -> String {
    guard let mapping = package.mappings[id] else {
      throw NeovimAdapterError.missingMapping
    }
    guard
      !mapping.isEmpty,
      mapping.allSatisfy({
        $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-" || $0 == "_")
      })
    else {
      throw NeovimAdapterError.invalidMapping(mapping)
    }
    return """
      -- Generated by Macarchy. Do not edit.
      return {
        generation_id = "\(generationID)",
        theme_id = "\(package.id)",
        colorscheme = "\(mapping)",
      }

      """
  }

  private func readConfiguration() throws -> String {
    let data: Data
    do {
      data = try BoundedRegularFile.read(at: configurationURL).data
    } catch BoundedRegularFileError.tooLarge {
      throw NeovimAdapterError.configurationTooLarge(configurationURL)
    } catch {
      throw NeovimAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard let configuration = String(data: data, encoding: .utf8) else {
      throw NeovimAdapterError.cannotReadConfiguration(configurationURL)
    }
    return configuration
  }

  private static func containsLine(_ expected: String, in text: String) -> Bool {
    text.split(separator: "\n").contains {
      $0.trimmingCharacters(in: .whitespaces) == expected
    }
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, NeovimAdapterError.missingIntegration:
      true
    default:
      false
    }
  }
}
