import Darwin
import Foundation
import TOMLDecoder

enum StarshipAdapterError: Error, CustomStringConvertible, Sendable {
  case behaviorOwnsTheme(URL)
  case bridgeDoesNotMatch(URL)
  case bridgeIsNotRegularFile(URL)
  case cannotPublishBridge(URL, String)
  case cannotReadBehavior(URL)
  case cannotReadBridge(URL, String)
  case configurationTooLarge(URL)
  case controlUnavailable(URL)
  case invalidBehavior(URL)

  var description: String {
    switch self {
    case .behaviorOwnsTheme(let url):
      "Starship behavior source at \(url.path) must not define palette or palettes"
    case .bridgeDoesNotMatch(let url):
      "Starship bridge at \(url.path) does not match the active generation and behavior source"
    case .bridgeIsNotRegularFile(let url):
      "Starship bridge at \(url.path) must be an ordinary regular file"
    case .cannotPublishBridge(let url, let cause):
      "Cannot publish Starship bridge at \(url.path): \(cause)"
    case .cannotReadBehavior(let url):
      "Cannot read Starship behavior source at \(url.path)"
    case .cannotReadBridge(let url, let cause):
      "Cannot read Starship bridge at \(url.path): \(cause)"
    case .configurationTooLarge(let url):
      "Starship configuration at \(url.path) exceeds 1 MiB"
    case .controlUnavailable(let url):
      "Starship is not executable at \(url.path)"
    case .invalidBehavior(let url):
      "Starship behavior source at \(url.path) is not valid TOML"
    }
  }
}

package struct StarshipAdapter: Sendable {
  static let id = "starship"
  package static let bridgePath = "state/adapters/starship.toml"
  static let outputPath = "generated/starship.toml"
  static let paletteName = "macarchy_current"
  static let rendererVersion = 1
  static let liveExecutableURL = URL(filePath: "/opt/homebrew/bin/starship")

  let root: URL
  let configurationURL: URL
  let behaviorURL: URL
  let executableURL: URL
  let controlIsAvailable: @Sendable () -> Bool
  let processRunner: ProcessRunner

  private var bridgeURL: URL {
    root.appending(path: Self.bridgePath)
  }

  func preflight() throws {
    guard controlIsAvailable() else {
      throw StarshipAdapterError.controlUnavailable(executableURL)
    }
    try validateConfigurationLink()
    _ = try readBehavior()
  }

  func inspection() -> AdapterInspection {
    do {
      try preflight()
      do {
        try ActivationLock(root: root).withLock {
          let desired = try desiredConfiguration()
          guard try readBridge() == desired else {
            throw StarshipAdapterError.bridgeDoesNotMatch(bridgeURL)
          }
        }
      } catch ReconciliationStatusError.noActiveGeneration {
        // The stable seam can be healthy before the first bridge exists.
      }
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        message: "Starship reads the active palette on the next prompt"
      )
    } catch {
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        status: Self.isIntegrationDrift(error) ? .drifted : .failed,
        message: String(describing: error)
      )
    }
  }

  func reconciliation() -> AdapterReconciliation {
    AdapterReconciliation(id: Self.id, requirement: .required) {
      let bridgeOutcome: AdapterOutcome? = try ActivationLock(root: root).withLock {
        do {
          try preflight()
        } catch {
          return AdapterOutcome(
            status: Self.isIntegrationDrift(error) ? .drifted : .failed,
            message: String(describing: error)
          )
        }
        do {
          try publishBridge(desiredConfiguration())
        } catch {
          return AdapterOutcome(status: .failed, message: String(describing: error))
        }
        return nil
      }
      if let bridgeOutcome { return bridgeOutcome }

      let result = try processRunner.run(
        ProcessRequest(
          executableURL: executableURL,
          arguments: ["print-config"],
          timeout: 2,
          environmentOverrides: ["STARSHIP_CONFIG": bridgeURL.path]
        )
      )
      let selection = "palette = \"\(Self.paletteName)\""
      guard result.terminationStatus == 0, result.output.contains(selection) else {
        return AdapterOutcome(
          status: .failed,
          message: result.output.isEmpty
            ? "Starship rejected the active palette configuration" : result.output
        )
      }
      return AdapterOutcome(
        status: .applied,
        message: "Starship prompts use the active palette"
      )
    }
  }

  static func render(package: ThemePackage) -> String {
    let ansi = package.terminal.ansi
    return """
      # Generated by Macarchy. Do not edit.
      [palettes.\(paletteName)]
      blue = "\(ansi[4].rawValue)"
      bright-black = "\(ansi[8].rawValue)"
      cyan = "\(ansi[6].rawValue)"
      green = "\(ansi[2].rawValue)"
      purple = "\(ansi[5].rawValue)"
      red = "\(ansi[1].rawValue)"
      yellow = "\(ansi[3].rawValue)"

      """
  }

  private func desiredConfiguration() throws -> Data {
    let behavior = try readBehavior().trimmingCharacters(in: .whitespacesAndNewlines)
    let palette = try activePalette().trimmingCharacters(in: .whitespacesAndNewlines)
    return Data(
      """
      # Generated by Macarchy from the dotfiles-owned behavior source. Do not edit.
      palette = "\(Self.paletteName)"

      \(behavior)

      \(palette)

      """.utf8
    )
  }

  private func activePalette() throws -> String {
    let manifest = try ReconciliationStatusStore(root: root).activeManifest()
    let data = try BoundedRegularFile.read(
      at: root.appending(
        path: "generations/\(manifest.generationID)/\(Self.outputPath)"
      )
    ).data
    guard let palette = String(data: data, encoding: .utf8) else {
      throw StarshipAdapterError.bridgeDoesNotMatch(bridgeURL)
    }
    return palette
  }

  private func readBehavior() throws -> String {
    let data: Data
    do {
      data = try BoundedRegularFile.read(at: behaviorURL).data
    } catch BoundedRegularFileError.tooLarge {
      throw StarshipAdapterError.configurationTooLarge(behaviorURL)
    } catch {
      throw StarshipAdapterError.cannotReadBehavior(behaviorURL)
    }
    guard let behavior = String(data: data, encoding: .utf8) else {
      throw StarshipAdapterError.cannotReadBehavior(behaviorURL)
    }
    let ownership: StarshipThemeOwnership
    do {
      ownership = try TOMLDecoder().decode(StarshipThemeOwnership.self, from: behavior)
    } catch {
      throw StarshipAdapterError.invalidBehavior(behaviorURL)
    }
    guard ownership.palette == nil, ownership.palettes == nil else {
      throw StarshipAdapterError.behaviorOwnsTheme(behaviorURL)
    }
    return behavior
  }

  private func validateConfigurationLink() throws {
    let firstDestination: String
    do {
      firstDestination = try FileManager.default.destinationOfSymbolicLink(
        atPath: configurationURL.path
      )
    } catch {
      throw CanonicalThemeLinkError.notSymbolicLink(configurationURL)
    }

    var resolved = Self.destinationURL(firstDestination, from: configurationURL)
    var visited = Set([configurationURL.path])
    while visited.insert(resolved.path).inserted,
      let next = try? FileManager.default.destinationOfSymbolicLink(atPath: resolved.path)
    {
      resolved = Self.destinationURL(next, from: resolved)
    }
    guard resolved == bridgeURL else {
      throw CanonicalThemeLinkError.wrongDestination(
        configurationURL,
        expected: bridgeURL.path
      )
    }
  }

  private static func destinationURL(_ destination: String, from link: URL) -> URL {
    if destination.hasPrefix("/") {
      return URL(filePath: destination).standardizedFileURL
    }
    return link.deletingLastPathComponent().appending(path: destination).standardizedFileURL
  }

  private func readBridge() throws -> Data {
    do {
      return try BoundedRegularFile.read(at: bridgeURL).data
    } catch BoundedRegularFileError.notRegular {
      throw StarshipAdapterError.bridgeIsNotRegularFile(bridgeURL)
    } catch BoundedRegularFileError.system(operation: "open", code: ELOOP) {
      throw StarshipAdapterError.bridgeIsNotRegularFile(bridgeURL)
    } catch BoundedRegularFileError.system(operation: "open", code: ENOENT),
      BoundedRegularFileError.tooLarge
    {
      throw StarshipAdapterError.bridgeDoesNotMatch(bridgeURL)
    } catch {
      throw StarshipAdapterError.cannotReadBridge(bridgeURL, String(describing: error))
    }
  }

  private func publishBridge(_ data: Data) throws {
    do {
      try FileManager.default.createDirectory(
        at: bridgeURL.deletingLastPathComponent(),
        withIntermediateDirectories: true
      )
      try data.write(to: bridgeURL, options: .atomic)
    } catch {
      throw StarshipAdapterError.cannotPublishBridge(bridgeURL, String(describing: error))
    }
    guard try readBridge() == data else {
      throw StarshipAdapterError.bridgeDoesNotMatch(bridgeURL)
    }
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, StarshipAdapterError.behaviorOwnsTheme,
      StarshipAdapterError.bridgeDoesNotMatch:
      true
    default:
      false
    }
  }
}

private struct StarshipThemeOwnership: Decodable {
  let palette: String?
  let palettes: [String: [String: String]]?
}
