import Foundation
import TOMLDecoder

enum TuicrAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadConfiguration(URL)
  case controlUnavailable(URL)
  case invalidConfiguration(URL)
  case wrongThemeSelection(String)

  var description: String {
    switch self {
    case .cannotReadConfiguration(let url):
      "Cannot read tuicr configuration at \(url.path)"
    case .controlUnavailable(let url):
      "tuicr is not executable at \(url.path)"
    case .invalidConfiguration(let url):
      "tuicr configuration at \(url.path) is not valid TOML"
    case .wrongThemeSelection(let expected):
      "tuicr configuration must select theme \"\(expected)\""
    }
  }
}

struct TuicrAdapter: Sendable {
  static let id = "tuicr"
  static let outputPath = "generated/tuicr.toml"
  static let rendererVersion = 1
  static let themeName = "macarchy-current"
  static let liveExecutableURL = URL(filePath: "/opt/homebrew/bin/tuicr")

  let root: URL
  let configurationDirectoryURL: URL
  let executableURL: URL
  let controlIsAvailable: @Sendable () -> Bool

  private var configurationURL: URL {
    configurationDirectoryURL.appending(path: "config.toml")
  }

  private var themeLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: configurationDirectoryURL.appending(path: "themes/\(Self.themeName).toml"),
      destination: root.appending(path: "current/\(Self.outputPath)")
    )
  }

  private var syntaxLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: configurationDirectoryURL.appending(path: "themes/\(Self.themeName).tmTheme"),
      destination: root.appending(path: "current/\(BatAdapter.outputPath)")
    )
  }

  func preflight() throws {
    guard controlIsAvailable() else {
      throw TuicrAdapterError.controlUnavailable(executableURL)
    }
    try themeLink.validate()
    try syntaxLink.validate()
    guard try selectedTheme() == Self.themeName else {
      throw TuicrAdapterError.wrongThemeSelection(Self.themeName)
    }
  }

  func inspection() -> AdapterInspection {
    do {
      try preflight()
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        message: "Fresh tuicr sessions use the generated palette"
      )
    } catch {
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        status: Self.isIntegrationDrift(error) ? .drifted : .failed,
        message: String(describing: error)
      )
    }
  }

  func reconciliation() -> AdapterReconciliation {
    AdapterReconciliation(id: Self.id, requirement: .required) {
      do {
        try preflight()
        return AdapterOutcome(
          status: .restartRequired,
          message: "Restart tuicr to use the active palette"
        )
      } catch {
        return AdapterOutcome(
          status: Self.isIntegrationDrift(error) ? .drifted : .failed,
          message: String(describing: error)
        )
      }
    }
  }

  static func render(package: ThemePackage) -> String {
    let semantic = package.semantic
    return """
      # Generated by Macarchy. Do not edit.
      panel_bg = "\(semantic.background.rawValue)"
      bg_highlight = "\(semantic.selection.rawValue)"
      fg_primary = "\(semantic.text.rawValue)"
      fg_secondary = "\(semantic.mutedText.rawValue)"
      fg_dim = "\(semantic.overlay.rawValue)"

      diff_add = "\(semantic.success.rawValue)"
      diff_add_bg = "\(semantic.surface.rawValue)"
      diff_del = "\(semantic.error.rawValue)"
      diff_del_bg = "\(semantic.overlay.rawValue)"
      diff_context = "\(semantic.text.rawValue)"
      diff_hunk_header = "\(semantic.info.rawValue)"
      expanded_context_fg = "\(semantic.mutedText.rawValue)"

      syntax_add_bg = "\(semantic.surface.rawValue)"
      syntax_del_bg = "\(semantic.overlay.rawValue)"
      syntax_theme = "\(themeName).tmTheme"

      file_added = "\(semantic.success.rawValue)"
      file_modified = "\(semantic.warning.rawValue)"
      file_deleted = "\(semantic.error.rawValue)"
      file_renamed = "\(semantic.accent.rawValue)"
      reviewed = "\(semantic.success.rawValue)"
      pending = "\(semantic.warning.rawValue)"

      comment_note = "\(semantic.info.rawValue)"
      comment_suggestion = "\(semantic.accent.rawValue)"
      comment_issue = "\(semantic.error.rawValue)"
      comment_praise = "\(semantic.success.rawValue)"

      border_focused = "\(semantic.accent.rawValue)"
      border_unfocused = "\(semantic.border.rawValue)"
      status_bar_bg = "\(semantic.surface.rawValue)"
      cursor_color = "\(semantic.warning.rawValue)"
      cursor_line_bg = "\(semantic.selection.rawValue)"
      branch_name = "\(semantic.accent.rawValue)"
      help_indicator = "\(semantic.mutedText.rawValue)"

      message_info_fg = "\(semantic.background.rawValue)"
      message_info_bg = "\(semantic.info.rawValue)"
      message_warning_fg = "\(semantic.background.rawValue)"
      message_warning_bg = "\(semantic.warning.rawValue)"
      message_error_fg = "\(semantic.background.rawValue)"
      message_error_bg = "\(semantic.error.rawValue)"
      update_badge_fg = "\(semantic.background.rawValue)"
      update_badge_bg = "\(semantic.warning.rawValue)"
      mode_fg = "\(semantic.background.rawValue)"
      mode_bg = "\(semantic.accent.rawValue)"

      """
  }

  private func selectedTheme() throws -> String? {
    let data: Data
    do {
      data = try BoundedRegularFile.read(at: configurationURL.resolvingSymlinksInPath()).data
    } catch {
      throw TuicrAdapterError.cannotReadConfiguration(configurationURL)
    }
    guard let configuration = String(data: data, encoding: .utf8) else {
      throw TuicrAdapterError.cannotReadConfiguration(configurationURL)
    }
    do {
      return try TOMLDecoder().decode(Configuration.self, from: configuration).theme
    } catch {
      throw TuicrAdapterError.invalidConfiguration(configurationURL)
    }
  }

  private struct Configuration: Decodable {
    let theme: String?
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, TuicrAdapterError.wrongThemeSelection:
      true
    default:
      false
    }
  }
}
