import Foundation

enum YaziAdapterError: Error, CustomStringConvertible, Sendable {
  case cannotReadConfiguration(URL)
  case configurationTooLarge(URL)
  case controlUnavailable(URL)
  case missingFlavorSelection(String)

  var description: String {
    switch self {
    case .cannotReadConfiguration(let url):
      "Cannot read Yazi theme configuration at \(url.path)"
    case .configurationTooLarge(let url):
      "Yazi theme configuration at \(url.path) exceeds 1 MiB"
    case .controlUnavailable(let url):
      "Yazi control is not executable at \(url.path)"
    case .missingFlavorSelection(let selection):
      "Yazi theme configuration must select \(selection)"
    }
  }
}

struct YaziAdapter: Sendable {
  static let id = "yazi"
  static let flavorOutputPath = "generated/yazi-flavor.toml"
  static let syntaxOutputPath = "generated/yazi.tmTheme"
  static let rendererVersion = 1
  static let flavorName = "macarchy-current"
  static let liveExecutableURL = URL(filePath: "/opt/homebrew/bin/yazi")
  static let liveControlURL = URL(filePath: "/opt/homebrew/bin/ya")

  private static let killallURL = URL(filePath: "/usr/bin/killall")

  let root: URL
  let configurationDirectoryURL: URL
  let executableURL: URL
  let controlURL: URL
  let controlsAreAvailable: @Sendable () -> Bool
  let processRunner: ProcessRunner

  private var themeConfigurationURL: URL {
    configurationDirectoryURL.appending(path: "theme.toml")
  }

  private var flavorDirectoryURL: URL {
    configurationDirectoryURL.appending(
      path: "flavors/\(Self.flavorName).yazi", directoryHint: .isDirectory)
  }

  private var flavorLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: flavorDirectoryURL.appending(path: "flavor.toml"),
      destination: root.appending(path: "current/\(Self.flavorOutputPath)")
    )
  }

  private var syntaxLink: CanonicalThemeLink {
    CanonicalThemeLink(
      url: flavorDirectoryURL.appending(path: "tmtheme.xml"),
      destination: root.appending(path: "current/\(Self.syntaxOutputPath)")
    )
  }

  func preflight() throws {
    guard controlsAreAvailable() else {
      throw YaziAdapterError.controlUnavailable(
        FileManager.default.isExecutableFile(atPath: executableURL.path)
          ? controlURL : executableURL
      )
    }
    try flavorLink.validate()
    try syntaxLink.validate()

    let configuration = try readThemeConfiguration()
    guard Self.selectsFlavor(in: configuration) else {
      throw YaziAdapterError.missingFlavorSelection(
        "[flavor] dark = \"\(Self.flavorName)\""
      )
    }
  }

  func inspection() -> AdapterInspection {
    do {
      try preflight()
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        message: "Yazi uses the generated flavor and supports live theme reload"
      )
    } catch {
      return AdapterInspection(
        adapterID: Self.id,
        requirement: .required,
        status: Self.isIntegrationDrift(error) ? .drifted : .failed,
        message: String(describing: error)
      )
    }
  }

  func reconciliation() -> AdapterReconciliation {
    AdapterReconciliation(id: Self.id, requirement: .required) {
      do {
        try preflight()
      } catch {
        return AdapterOutcome(
          status: Self.isIntegrationDrift(error) ? .drifted : .failed,
          message: String(describing: error)
        )
      }

      let running = try processRunner.run(
        ProcessRequest(executableURL: Self.killallURL, arguments: ["-0", "yazi"])
      )
      guard running.terminationStatus == 0 else {
        return AdapterOutcome(
          status: .applied,
          message: "Yazi will use the active palette on next launch"
        )
      }

      let reload = try processRunner.run(
        ProcessRequest(
          executableURL: controlURL,
          arguments: ["emit-to", "0", "theme"],
          timeout: 1
        )
      )
      if reload.terminationStatus == 0 {
        return AdapterOutcome(status: .applied, message: "Running Yazi sessions reloaded")
      }

      let stillRunning = try processRunner.run(
        ProcessRequest(executableURL: Self.killallURL, arguments: ["-0", "yazi"])
      )
      guard stillRunning.terminationStatus == 0 else {
        return AdapterOutcome(
          status: .applied,
          message: "Yazi will use the active palette on next launch"
        )
      }
      return AdapterOutcome(
        status: .failed,
        message: reload.output.isEmpty ? "Yazi rejected its theme reload action" : reload.output
      )
    }
  }

  static func renderFlavor(package: ThemePackage) -> String {
    let semantic = package.semantic
    let ansi = package.terminal.ansi
    return """
      # Generated by Macarchy. Do not edit.

      [app]
      overall = { bg = "\(semantic.background.rawValue)" }

      [mgr]
      cwd = { fg = "\(semantic.info.rawValue)" }
      find_keyword = { fg = "\(semantic.warning.rawValue)", bold = true, italic = true, underline = true }
      find_position = { fg = "\(semantic.accent.rawValue)", bold = true, italic = true }
      marker_copied = { fg = "\(semantic.success.rawValue)", bg = "\(semantic.success.rawValue)" }
      marker_cut = { fg = "\(semantic.error.rawValue)", bg = "\(semantic.error.rawValue)" }
      marker_marked = { fg = "\(semantic.info.rawValue)", bg = "\(semantic.info.rawValue)" }
      marker_selected = { fg = "\(semantic.warning.rawValue)", bg = "\(semantic.warning.rawValue)" }
      count_copied = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.success.rawValue)" }
      count_cut = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.error.rawValue)" }
      count_selected = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.warning.rawValue)" }
      border_style = { fg = "\(semantic.border.rawValue)" }

      [tabs]
      active = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.accent.rawValue)", bold = true }
      inactive = { fg = "\(semantic.mutedText.rawValue)", bg = "\(semantic.surface.rawValue)" }

      [mode]
      normal_main = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.accent.rawValue)", bold = true }
      normal_alt = { fg = "\(semantic.accent.rawValue)", bg = "\(semantic.surface.rawValue)" }
      select_main = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.info.rawValue)", bold = true }
      select_alt = { fg = "\(semantic.info.rawValue)", bg = "\(semantic.surface.rawValue)" }
      unset_main = { fg = "\(semantic.background.rawValue)", bg = "\(semantic.warning.rawValue)", bold = true }
      unset_alt = { fg = "\(semantic.warning.rawValue)", bg = "\(semantic.surface.rawValue)" }

      [status]
      perm_sep = { fg = "\(semantic.mutedText.rawValue)" }
      perm_type = { fg = "\(semantic.info.rawValue)" }
      perm_read = { fg = "\(semantic.warning.rawValue)" }
      perm_write = { fg = "\(semantic.error.rawValue)" }
      perm_exec = { fg = "\(semantic.success.rawValue)" }
      progress_label = { fg = "\(semantic.text.rawValue)", bold = true }
      progress_normal = { fg = "\(semantic.success.rawValue)", bg = "\(semantic.overlay.rawValue)" }
      progress_error = { fg = "\(semantic.warning.rawValue)", bg = "\(semantic.error.rawValue)" }

      [pick]
      border = { fg = "\(semantic.accent.rawValue)" }
      active = { fg = "\(semantic.accent.rawValue)", bold = true }

      [input]
      border = { fg = "\(semantic.accent.rawValue)" }
      value = { fg = "\(semantic.text.rawValue)" }
      selected = { bg = "\(semantic.selection.rawValue)" }

      [cmp]
      border = { fg = "\(semantic.accent.rawValue)" }

      [tasks]
      border = { fg = "\(semantic.accent.rawValue)" }
      hovered = { fg = "\(semantic.accent.rawValue)", bold = true }

      [which]
      border = { fg = "\(semantic.accent.rawValue)" }
      cand = { fg = "\(semantic.info.rawValue)" }
      rest = { fg = "\(semantic.mutedText.rawValue)" }
      desc = { fg = "\(semantic.accent.rawValue)" }
      separator_style = { fg = "\(semantic.border.rawValue)" }

      [help]
      on = { fg = "\(semantic.info.rawValue)" }
      run = { fg = "\(semantic.accent.rawValue)" }
      hovered = { bg = "\(semantic.selection.rawValue)", bold = true }
      footer = { fg = "\(semantic.surface.rawValue)", bg = "\(semantic.text.rawValue)" }

      [spot]
      border = { fg = "\(semantic.accent.rawValue)" }
      title = { fg = "\(semantic.accent.rawValue)" }
      tbl_col = { fg = "\(semantic.info.rawValue)" }
      tbl_cell = { fg = "\(semantic.text.rawValue)", bg = "\(semantic.surface.rawValue)" }

      [notify]
      title_info = { fg = "\(semantic.success.rawValue)" }
      title_warn = { fg = "\(semantic.warning.rawValue)" }
      title_error = { fg = "\(semantic.error.rawValue)" }

      [filetype]
      rules = [
        { mime = "**/image/*", fg = "\(semantic.info.rawValue)" },
        { mime = "**/{audio,video}/*", fg = "\(semantic.warning.rawValue)" },
        { mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "\(semantic.accent.rawValue)" },
        { mime = "**/application/{pdf,doc,rtf}", fg = "\(semantic.success.rawValue)" },
        { url = "*", fg = "\(semantic.text.rawValue)" },
        { url = "*/", fg = "\(ansi[4].rawValue)" },
      ]

      """
  }

  private func readThemeConfiguration() throws -> String {
    let data: Data
    do {
      data = try BoundedRegularFile.read(at: themeConfigurationURL).data
    } catch BoundedRegularFileError.tooLarge {
      throw YaziAdapterError.configurationTooLarge(themeConfigurationURL)
    } catch {
      throw YaziAdapterError.cannotReadConfiguration(themeConfigurationURL)
    }
    guard let configuration = String(data: data, encoding: .utf8) else {
      throw YaziAdapterError.cannotReadConfiguration(themeConfigurationURL)
    }
    return configuration
  }

  private static func selectsFlavor(in configuration: String) -> Bool {
    var inFlavor = false
    var selections = [String]()
    for rawLine in configuration.split(separator: "\n") {
      let line =
        rawLine.split(separator: "#", maxSplits: 1).first?.trimmingCharacters(
          in: .whitespaces) ?? ""
      if line.hasPrefix("[") {
        inFlavor = line == "[flavor]"
      } else if inFlavor {
        let parts = line.split(separator: "=", maxSplits: 1).map {
          $0.trimmingCharacters(in: .whitespaces)
        }
        if parts.first == "dark" {
          selections.append(parts.count == 2 ? parts[1] : "")
        }
      }
    }
    return selections == ["\"\(flavorName)\""]
  }

  private static func isIntegrationDrift(_ error: any Error) -> Bool {
    switch error {
    case is CanonicalThemeLinkError, YaziAdapterError.missingFlavorSelection:
      true
    default:
      false
    }
  }
}
